services:
  frontend:
    build: ./frontend
    container_name: are-you-drunk-yet-frontend
    ports:
      - "8080:5001"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: are-you-drunk-yet-backend
    ports:
      - "5050:5050"
    restart: unless-stopped 