services:
  app:
    image: jheidt04/am-i-drunk:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - drunk-net
    deploy: 
      mode: replicated
      replicas: 1

networks:
  drunk-net:
    driver: overlay