version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: are-you-drunk-yet-frontend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: are-you-drunk-yet-backend
    restart: unless-stopped

  proxy:
    image: nginx:latest
    container_name: are-you-drunk-yet-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped 