services:
  frontend:
    build: ./frontend
    container_name: are-you-drunk-yet-frontend
    ports:
      - "80:5001"
    environment:
      - API_URL=http://backend:8000
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: are-you-drunk-yet-backend
    ports:
      - "8080:8000"
    restart: unless-stopped 